name: Manual Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true
        default: 2.0.0
      draft:
        description: Save the release as a draft first?
        required: false
        default: false
        type: boolean
      prerelease:
        description: Mark this build as a pre-release?
        required: false
        default: false
        type: boolean

permissions:
  contents: write

env:
  VERSION: ${{ inputs.version }}

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build v2dat
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Export asset list
        run: |
          echo "ASSET_FILES=$(ls dist/assets/*.tar.gz | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: v2dat-${{ env.VERSION }}
          path: ${{ env.ASSET_FILES }}

      - name: Create or update release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          draft: ${{ inputs.draft }}
          prerelease: ${{ inputs.prerelease }}
          files: ${{ env.ASSET_FILES }}
